=== Unidata/awips2-ncep/viz/gov.noaa.nws.ncep.viz.cloudHeight/localization/ncep/CloudHeight/SoundingModels.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:element name="SoundingModels">
        <xsd:complexType>
            <xsd:sequence maxOccurs="1" minOccurs="1">
                <xsd:element ref="SoundingModel" 
                            maxOccurs="unbounded" 
                            minOccurs="1">
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="SoundingModel">
        <xsd:complexType>
            <xsd:sequence> 
                <xsd:element name="Name" type="xsd:string"/>

                <xsd:element name="swLat" minOccurs="0"
                             type="xsd:double"/>
                <xsd:element name="swLon" minOccurs="0"
                             type="xsd:double"/>
                <xsd:element name="neLat" minOccurs="0"
                             type="xsd:double"/>
                <xsd:element name="neLon" minOccurs="0"
                             type="xsd:double"/>

                <xsd:element name="validStartDate" minOccurs="0"
                             type="xsd:string"/>
                <xsd:element name="validEndDate" minOccurs="0"
                             type="xsd:string"/>

                <xsd:element ref="SoundingLevels" 
                     maxOccurs="1" minOccurs="1"/>
            </xsd:sequence>
         </xsd:complexType>
    </xsd:element>

    <xsd:element name="SoundingLevels">
        <xsd:complexType>
            <xsd:sequence> 
                <xsd:element name="levelValues" minOccurs="1" 
                                                maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence> 
                            <xsd:element name="pressure" type="xsd:double"
                                         minOccurs="1" maxOccurs="1"/>
                            <xsd:element name="temperature" type="xsd:double"
                                         minOccurs="1" maxOccurs="1"/>
                            <xsd:element name="height" type="xsd:double"
                                         minOccurs="1" maxOccurs="1"/>
                        </xsd:sequence> 
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
         </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Unidata/awips2-ncep/viz/gov.noaa.nws.ncep.viz.cloudHeight/localization/ncep/CloudHeight/SoundingModels.xml
<?xml version="1.0" encoding="UTF-8"?>
<SoundingModels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SoundingModels.xsd">
   <SoundingModel>
      <Name>Standard</Name>
      <swLat>-90.0</swLat>
      <swLon>0.0</swLon>
      <neLat>90.0</neLat>
      <neLon>360.0</neLon>
      <validStartDate/>
      <validEndDate/>

      <SoundingLevels>
        <levelValues>
           <pressure>1013.25</pressure>
           <temperature>15.00</temperature>
           <height>0.00</height>
        </levelValues>
        <levelValues>
           <pressure>1000.00</pressure>
           <temperature>14.20</temperature>
           <height>111.00</height>
        </levelValues>
        <levelValues>
           <pressure>975.00</pressure>
           <temperature>13.00</temperature>
           <height>323.00</height>
        </levelValues>
        <levelValues>
           <pressure>950.00</pressure>
           <temperature>11.40</temperature>
           <height>540.00</height>
        </levelValues>
        <levelValues>
           <pressure>925.00</pressure>
           <temperature>10.00</temperature>
           <height>762.00</height>
        </levelValues>
        <levelValues>
           <pressure>900.00</pressure>
           <temperature>8.60</temperature>
           <height>989.00</height>
        </levelValues>
        <levelValues>
           <pressure>875.00</pressure>
           <temperature>7.00</temperature>
           <height>1220.00 </height>
        </levelValues>
        <levelValues>
           <pressure>850.00</pressure>
           <temperature>5.60</temperature>
           <height>1457.00</height>
        </levelValues>
        <levelValues>
           <pressure>825.00</pressure>
           <temperature>4.00</temperature>
           <height>1700.00</height>
        </levelValues>
        <levelValues>
           <pressure>800.00</pressure>
           <temperature>2.40</temperature>
           <height>1949.00</height>
        </levelValues>
        <levelValues>
           <pressure>775.00</pressure>
           <temperature>0.60</temperature>
           <height>2204.00</height>
        </levelValues>
        <levelValues>
           <pressure>750.00</pressure>
           <temperature>-1.00</temperature>
           <height>2466.00</height>
        </levelValues>
        <levelValues>
           <pressure>725.00</pressure>
           <temperature>-2.70</temperature>
           <height>2735.00</height>
        </levelValues>
        <levelValues>
           <pressure>700.00</pressure>
           <temperature>-4.50</temperature>
           <height>3012.00</height>
        </levelValues>
        <levelValues>
           <pressure>675.00</pressure>
           <temperature>-6.50</temperature>
           <height>3297.00</height>
        </levelValues>
        <levelValues>
           <pressure>650.00</pressure>
           <temperature>-8.30</temperature>
           <height>3591.00</height>
        </levelValues>
        <levelValues>
           <pressure>625.00</pressure>
           <temperature>-10.30</temperature>
           <height>3894.00</height>
        </levelValues>
        <levelValues>
           <pressure>600.00</pressure>
           <temperature>-12.30</temperature>
           <height>4206.00</height>
        </levelValues>
        <levelValues>
           <pressure>575.00</pressure>
           <temperature>-14.50</temperature>
           <height>4530.00</height>
        </levelValues>
        <levelValues>
           <pressure>550.00</pressure>
           <temperature>-16.70</temperature>
           <height>4865.00</height>
        </levelValues>
        <levelValues>
           <pressure>525.00</pressure>
           <temperature>-18.90</temperature>
           <height>5213.00</height>
        </levelValues>
        <levelValues>
           <pressure>500.00</pressure>
           <temperature>-21.30</temperature>
           <height>5574.00</height>
        </levelValues>
        <levelValues>
           <pressure>475.00</pressure>
           <temperature>-23.70</temperature>
           <height>5951.00</height>
        </levelValues>
        <levelValues>
           <pressure>450.00</pressure>
           <temperature>-26.30</temperature>
           <height>6344.00</height>
        </levelValues>
        <levelValues>
           <pressure>425.00</pressure>
           <temperature>-28.90</temperature>
           <height>6755.00</height>
        </levelValues>
        <levelValues>
           <pressure>400.00</pressure>
           <temperature>-31.70</temperature>
           <height>7185.00</height>
        </levelValues>
        <levelValues>
           <pressure>375.00</pressure>
           <temperature>-34.70</temperature>
           <height>7639.00</height>
        </levelValues>
        <levelValues>
           <pressure>350.00</pressure>
           <temperature>-37.70</temperature>
           <height>8117.00</height>
        </levelValues>
        <levelValues>
           <pressure>325.00</pressure>
           <temperature>-41.10</temperature>
           <height>8624.00</height>
        </levelValues>
        <levelValues>
           <pressure>300.00</pressure>
           <temperature>-44.50</temperature>
           <height>9164.00</height>
        </levelValues>
        <levelValues>
           <pressure>275.00</pressure>
           <temperature>-48.30</temperature>
           <height>9741.00</height>
        </levelValues>
        <levelValues>
           <pressure>250.00</pressure>
           <temperature>-52.30</temperature>
           <height>10363.00</height>
        </levelValues>
        <levelValues>
           <pressure>226.00</pressure>
           <temperature>-56.50</temperature>
           <height>11000.00</height>
        </levelValues>
        <levelValues>
           <pressure>225.00</pressure>
           <temperature>-56.50</temperature>
           <height>11037.00</height>
        </levelValues>
        <levelValues>
           <pressure>200.00</pressure>
           <temperature>-56.50</temperature>
           <height>11784.00</height>
        </levelValues>
        <levelValues>
           <pressure>175.00</pressure>
           <temperature>-56.50</temperature>
           <height>12631.00</height>
        </levelValues>
        <levelValues>
           <pressure>150.00</pressure>
           <temperature>-56.50</temperature>
           <height>13608.00</height>
        </levelValues>
        <levelValues>
           <pressure>125.00</pressure>
           <temperature>-56.50</temperature>
           <height>14765.00</height>
        </levelValues>
        <levelValues>
           <pressure>100.00</pressure>
           <temperature>-56.50</temperature>
           <height>16180.00</height>
        </levelValues>
        <levelValues>
           <pressure>75.00</pressure>
           <temperature>-56.50</temperature>
           <height>18004.00</height>
        </levelValues>
        <levelValues>
           <pressure>55.00</pressure>
           <temperature>-56.50</temperature>
           <height>20000.00</height>
        </levelValues>
        <levelValues>
           <pressure>50.00</pressure>
           <temperature>-55.90</temperature>
           <height>20576.00</height>
        </levelValues>
        <levelValues>
           <pressure>25.00</pressure>
           <temperature>-51.50</temperature>
           <height>25029.00</height>
        </levelValues>
      </SoundingLevels>
   </SoundingModel> <!-- Standard -->

   <SoundingModel>
      <Name>Winter-15deg</Name>
      <swLat>15.0</swLat>
      <swLon>0.0</swLon>
      <neLat>90.0</neLat>
      <neLon>360.0</neLon>
      <validStartDate>winter</validStartDate>
      <validEndDate>winter</validEndDate>
      <SoundingLevels>
        <levelValues>
           <pressure>1013.00</pressure>
           <temperature>26.60</temperature>
           <height>0.00</height>
        </levelValues>
        <levelValues>
           <pressure>780.00</pressure>
           <temperature>14.00</temperature>
           <height>2300.00</height>
        </levelValues>
        <levelValues>
           <pressure>757.00</pressure>
           <temperature>13.80</temperature>
           <height>2500.00</height>
        </levelValues>
        <levelValues>
           <pressure>103.00</pressure>
           <temperature>-79.90</temperature>
           <height>16500.00</height>
        </levelValues>
        <levelValues>
           <pressure>67.00</pressure>
           <temperature>-99.90</temperature>
           <height>19450.00</height>
        </levelValues>
      </SoundingLevels>
   </SoundingModel>

   <SoundingModel>
      <Name>Winter-30deg</Name>
      <swLat>30.0</swLat>
      <swLon>0.0</swLon>
      <neLat>90.0</neLat>
      <neLon>360.0</neLon>
      <validStartDate>winter</validStartDate>
      <validEndDate>winter</validEndDate>
      <SoundingLevels>
        <levelValues>
           <pressure>1013.00</pressure>
           <temperature>14.00</temperature>
           <height>0.00</height>
        </levelValues>
        <levelValues>
           <pressure>804.00</pressure>
           <temperature>8.00</temperature>
           <height>2000.00</height>
        </levelValues>
        <levelValues>
           <pressure>203.00</pressure>
           <temperature>-56.90</temperature>
           <height>12000.00</height>
        </levelValues>
        <levelValues>
           <pressure>145.00</pressure>
           <temperature>-69.90</temperature>
           <height>14000.00</height>
        </levelValues>
        <levelValues>
           <pressure>112.00</pressure>
           <temperature>-79.90</temperature>
           <height>15540.00</height>
        </levelValues>
        <levelValues>
           <pressure>67.00</pressure>
           <temperature>-99.90</temperature>
           <height>18615.00</height>
        </levelValues>
      </SoundingLevels>
   </SoundingModel>

   <SoundingModel>
