=== Unidata/awips2-ncep/viz/gov.noaa.nws.ncep.viz.rsc.aww/localization/ncep/AWWTables/stns.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        elementFormDefault="qualified">

        <xsd:element name="stid">
                <xsd:annotation>
                        <xsd:documentation>The station ID</xsd:documentation>
                </xsd:annotation>

                <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="16"></xsd:maxLength>
                        </xsd:restriction>
                </xsd:simpleType>
        </xsd:element>

        <xsd:element name="stnnum">
                <xsd:annotation>
                        <xsd:documentation>The station number</xsd:documentation>
                </xsd:annotation>

                <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="10"></xsd:maxLength>
                        </xsd:restriction>
                </xsd:simpleType>
        </xsd:element>

        <xsd:element name="stnname">
                <xsd:annotation>
                        <xsd:documentation>The station name</xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="35"></xsd:maxLength>
                        </xsd:restriction>
                </xsd:simpleType>
        </xsd:element>

        <xsd:element name="state">
                <xsd:annotation>
                        <xsd:documentation>state</xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="2"></xsd:maxLength>
                        </xsd:restriction>
                </xsd:simpleType>
        </xsd:element>

        <xsd:element name="country">
                <xsd:annotation>
                        <xsd:documentation>country</xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="2"></xsd:maxLength>
                        </xsd:restriction>
                </xsd:simpleType>
        </xsd:element>
  
        <xsd:element name="latitude">
                <xsd:annotation>
                        <xsd:documentation>The latitude</xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                        <xsd:restriction base="xsd:float">
                                <xsd:maxInclusive value="90."></xsd:maxInclusive>
                                <xsd:minInclusive value="-90."></xsd:minInclusive>
                        </xsd:restriction>
                </xsd:simpleType>
        </xsd:element>

        <xsd:element name="longitude">
                <xsd:annotation>
                        <xsd:documentation>The longitude</xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                        <xsd:restriction base="xsd:float">
                                <xsd:maxInclusive value="180."></xsd:maxInclusive>
                                <xsd:minInclusive value="-180."></xsd:minInclusive>
                        </xsd:restriction>
                </xsd:simpleType>
        </xsd:element>

        <xsd:element name="elevation">
                <xsd:annotation>
                        <xsd:documentation>The elevation</xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                        <xsd:restriction base="xsd:integer">
                                <xsd:maxInclusive value="99999"></xsd:maxInclusive>
                                <xsd:minInclusive value="-9999"></xsd:minInclusive>
                        </xsd:restriction>
                </xsd:simpleType>
        </xsd:element>
   
        <xsd:element name="priority">
                <xsd:annotation>
                        <xsd:documentation>The priority</xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                        <xsd:restriction base="xsd:integer">
                                <xsd:maxInclusive value="99"></xsd:maxInclusive>
                                <xsd:minInclusive value="0"></xsd:minInclusive>
                        </xsd:restriction>
                </xsd:simpleType>
        </xsd:element>

        <xsd:element name="location">
                <xsd:annotation>
                        <xsd:documentation>Volcano location</xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="32"></xsd:maxLength>
                        </xsd:restriction>
                </xsd:simpleType>
        </xsd:element>

        <xsd:element name="wfo">
                <xsd:annotation>
                        <xsd:documentation>WFO</xsd:documentation>
                </xsd:annotation>
                <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                                <xsd:maxLength value="15"></xsd:maxLength>
                        </xsd:restriction>
                </xsd:simpleType>
        </xsd:element>
   
        <xsd:element name="stationList">
                <xsd:complexType>
                        <xsd:sequence maxOccurs="1" minOccurs="1">
                                <xsd:element ref="station" maxOccurs="unbounded" minOccurs="0"></xsd:element>
                        </xsd:sequence>
                </xsd:complexType>
        </xsd:element>

        <xsd:element name="station">
                <xsd:annotation>
                        <xsd:documentation>A station</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                        <xsd:sequence maxOccurs="1" minOccurs="1">
                                <xsd:element ref="stid" maxOccurs="1" minOccurs="0"></xsd:element>
                                <xsd:element ref="stnnum" maxOccurs="1" minOccurs="0"></xsd:element>
                                <xsd:element ref="stnname" maxOccurs="1" minOccurs="0"></xsd:element>
                                <xsd:element ref="state" maxOccurs="1" minOccurs="0"></xsd:element>
                                <xsd:element ref="country" maxOccurs="1" minOccurs="0"></xsd:element>
                                <xsd:element ref="latitude" maxOccurs="1" minOccurs="0"></xsd:element>
                                <xsd:element ref="longitude" maxOccurs="1" minOccurs="0"></xsd:element>
                                <xsd:element ref="elevation" maxOccurs="1" minOccurs="0"></xsd:element>
                                <xsd:element ref="priority" maxOccurs="1" minOccurs="0"></xsd:element>
                                <xsd:element ref="location" maxOccurs="1" minOccurs="0"></xsd:element>
                                <xsd:element ref="wfo" maxOccurs="1" minOccurs="0"></xsd:element>
                        </xsd:sequence>
                </xsd:complexType>
        </xsd:element>
</xsd:schema>

=== Unidata/awips2-ncep/viz/gov.noaa.nws.ncep.viz.localization/localization/ncep/Stations/volcano.xml
<?xml version="1.0" encoding="UTF-8"?>
<stationList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="stns.xsd">
<!--This is station location data-->
     <station>
          <stid>1402-08</stid>
          <stnnum>999999</stnnum>
          <stnname>Acatenango</stnname>
          <state></state>
          <country></country>
          <latitude> 14.50</latitude>
          <longitude>-90.88</longitude>
          <elevation>3976</elevation>
          <priority>0</priority>
          <location>Guatemala</location>
     </station>
     <station>
          <stid>1201-04</stid>
          <stnnum>999999</stnnum>
          <stnname>Adams</stnname>
          <state></state>
          <country></country>
          <latitude> 46.20</latitude>
          <longitude>-121.49</longitude>
          <elevation>3742</elevation>
          <priority>0</priority>
          <location>US-Washington</location>
     </station>
     <station>
          <stid>0803-17</stid>
          <stnnum>999999</stnnum>
          <stnname>Adatara</stnname>
          <state></state>
          <country></country>
          <latitude> 37.62</latitude>
          <longitude>140.28</longitude>
          <elevation>1718</elevation>
          <priority>0</priority>
          <location>Honshu-Japan</location>
     </station>
     <station>
          <stid>0804-16</stid>
          <stnnum>999999</stnnum>
          <stnname>Agrigan</stnname>
          <state></state>
          <country></country>
          <latitude> 18.77</latitude>
          <longitude>145.67</longitude>
          <elevation>965</elevation>
          <priority>0</priority>
          <location>Mariana_Is-C_Pacific</location>
     </station>
     <station>
          <stid>0604-02</stid>
          <stnnum>999999</stnnum>
          <stnname>Agung</stnname>
          <state></state>
          <country></country>
          <latitude> -8.34</latitude>
          <longitude>115.51</longitude>
          <elevation>3142</elevation>
          <priority>0</priority>
          <location>Lesser_Sunda_Is</location>
     </station>
     <station>
          <stid>1000-123</stid>
          <stnnum>999999</stnnum>
          <stnname>Akademia_Nauk</stnname>
          <state></state>
          <country></country>
          <latitude> 53.98</latitude>
          <longitude>159.45</longitude>
          <elevation>1180</elevation>
          <priority>0</priority>
          <location>Kamchatka</location>
     </station>
     <station>
          <stid>0805-07</stid>
          <stnnum>999999</stnnum>
          <stnname>Akan</stnname>
          <state></state>
          <country></country>
          <latitude> 43.38</latitude>
          <longitude>144.02</longitude>
          <elevation>1499</elevation>
          <priority>0</priority>
          <location>Hokkaido-Japan</location>
     </station>
     <station>
          <stid>0803-23</stid>
          <stnnum>999999</stnnum>
          <stnname>Akita-Komaga-take</stnname>
          <state></state>
          <country></country>
          <latitude> 39.75</latitude>
          <longitude>140.80</longitude>
          <elevation>1637</elevation>
          <priority>0</priority>
          <location>Honshu-Japan</location>
     </station>
     <station>
          <stid>0803-26</stid>
          <stnnum>999999</stnnum>
          <stnname>Akita-Yake-yama</stnname>
          <state></state>
          <country></country>
          <latitude> 39.97</latitude>
          <longitude>140.77</longitude>
          <elevation>1366</elevation>
          <priority>0</priority>
          <location>Honshu-Japan</location>
     </station>
     <station>
          <stid>1101-32</stid>
          <stnnum>999999</stnnum>
          <stnname>Akutan</stnname>
          <state></state>
          <country></country>
          <latitude> 54.13</latitude>
          <longitude>-165.97</longitude>
          <elevation>1303</elevation>
          <priority>0</priority>
          <location>Aleutian_Is</location>
     </station>
     <station>
          <stid>0900-39</stid>
          <stnnum>999999</stnnum>
          <stnname>Alaid</stnname>
          <state></state>
          <country></country>
          <latitude> 50.86</latitude>
          <longitude>155.55</longitude>
          <elevation>2339</elevation>
          <priority>0</priority>
          <location>Kuril_Is</location>
     </station>
     <station>
          <stid>0201-112</stid>
          <stnnum>999999</stnnum>
          <stnname>Alayta</stnname>
          <state></state>
          <country></country>
          <latitude> 12.88</latitude>
          <longitude> 40.57</longitude>
          <elevation>1501</elevation>
          <priority>0</priority>
          <location>Ethiopia</location>
     </station>
     <station>
          <stid>1503-04</stid>
          <stnnum>999999</stnnum>
          <stnname>Alcedo,_Volcan</stnname>
          <state></state>
          <country></country>
          <latitude> -0.43</latitude>
          <longitude>-91.12</longitude>
          <elevation>1130</elevation>
          <priority>0</priority>
          <location>Galapagos</location>
     </station>
     <station>
          <stid>0507-04</stid>
          <stnnum>999999</stnnum>
          <stnname>Ambrym</stnname>
          <state></state>
          <country></country>
          <latitude>-16.25</latitude>
          <longitude>168.12</longitude>
          <elevation>1334</elevation>
          <priority>0</priority>
          <location>Vanuatu-SW_Pacific</location>
     </station>
     <station>
          <stid>1101-19</stid>
          <stnnum>999999</stnnum>
          <stnname>Amukta</stnname>
          <state></state>
          <country></country>
          <latitude> 52.50</latitude>
          <longitude>-171.25</longitude>
          <elevation>1066</elevation>
          <priority>0</priority>
          <location>Aleutian_Is</location>
     </station>
     <station>
          <stid>0804-20</stid>
          <stnnum>999999</stnnum>
          <stnname>Anatahan</stnname>
          <state></state>
          <country></country>
          <latitude> 16.35</latitude>
          <longitude>145.67</longitude>
          <elevation>788</elevation>
          <priority>0</priority>
          <location>Mariana_Islands</location>
     </station>
     <station>
          <stid>1102-09</stid>
          <stnnum>999999</stnnum>
          <stnname>Aniakchak</stnname>
          <state></state>
          <country></country>
          <latitude> 56.88</latitude>
          <longitude>-158.17</longitude>
          <elevation>1341</elevation>
          <priority>0</priority>
          <location>Alaska_Peninsula</location>
     </station>
     <station>
          <stid>0507-03</stid>
          <stnnum>999999</stnnum>
          <stnname>Aoba</stnname>
          <state></state>
          <country></country>
          <latitude>-15.40</latitude>
          <longitude>167.83</longitude>
          <elevation>1496</elevation>
          <priority>0</priority>
          <location>Vanuatu-SW_Pacific</location>
     </station>
     <station>
          <stid>1505-107</stid>
          <stnnum>999999</stnnum>
          <stnname>Aracar</stnname>
          <state></state>
          <country></country>
          <latitude>-24.27</latitude>
          <longitude>-67.77</longitude>
          <elevation>6082</elevation>
          <priority>0</priority>
          <location>Argentina</location>
     </station>
     <station>
          <stid>0201-126</stid>
          <stnnum>999999</stnnum>
          <stnname>Ardoukoba</stnname>
          <state></state>
          <country></country>
          <latitude> 11.58</latitude>
          <longitude> 42.47</longitude>
          <elevation>298</elevation>
          <priority>0</priority>
          <location>Djibouti</location>
     </station>
     <station>
          <stid>1405-033</stid>
          <stnnum>999999</stnnum>
          <stnname>Arenal</stnname>
          <state></state>
          <country></country>
          <latitude> 10.46</latitude>
          <longitude>-84.70</longitude>
          <elevation>1657</elevation>
          <priority>0</priority>
          <location>Costa_Rica</location>
     </station>
     <station>
          <stid>0603-29</stid>
          <stnnum>999999</stnnum>
          <stnname>Arjuno-Welirang</stnname>
          <state></state>
          <country></country>
          <latitude> -7.73</latitude>
          <longitude>112.58</longitude>
          <elevation>3339</elevation>
          <priority>0</priority>
          <location>Java</location>
     </station>
     <station>
          <stid>0803-11</stid>
          <stnnum>999999</stnnum>
          <stnname>Asama</stnname>
          <state></state>
          <country></country>
          <latitude> 36.40</latitude>
          <longitude>138.53</longitude>
          <elevation>2560</elevation>
          <priority>0</priority>
          <location>Honshu-Japan</location>
     </station>
     <station>
          <stid>1703-06</stid>
          <stnnum>999999</stnnum>
          <stnname>Askja</stnname>
          <state></state>
          <country></country>
          <latitude> 65.03</latitude>
          <longitude>-16.75</longitude>
          <elevation>1516</elevation>
          <priority>0</priority>
          <location>Iceland-NE</location>
     </station>
     <station>
          <stid>0802-11</stid>
          <stnnum>999999</stnnum>
          <stnname>Aso</stnname>
          <state></state>
          <country></country>
          <latitude> 32.88</latitude>
          <longitude>131.10</longitude>
          <elevation>1592</elevation>
          <priority>0</priority>
          <location>Kyushu-Japan</location>
     </station>
     <station>
          <stid>0804-15</stid>
          <stnnum>999999</stnnum>
          <stnname>Asuncion</stnname>
          <state></state>
          <country></country>
          <latitude> 19.67</latitude>
