=== Unidata/awips2-ncep/viz/gov.noaa.nws.ncep.viz.localization/localization/ncep/PlotModels/plotModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xsd:element name="plotModel">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element ref="PlotModelElement" maxOccurs="unbounded" minOccurs="1">
            </xsd:element>
         </xsd:sequence>
         <xsd:attribute name="name" type="xsd:string"></xsd:attribute>
         <xsd:attribute name="plugin" type="xsd:string"></xsd:attribute>
         <xsd:attribute name="svgTemplate" type="xsd:string"></xsd:attribute>
      </xsd:complexType>
   </xsd:element>

    <xsd:element name="Color">
       <xsd:complexType>
            <xsd:attribute name="blue" use="required">
             <xsd:simpleType>
                <xsd:restriction base="xsd:int">
                   <xsd:minInclusive value="0"></xsd:minInclusive>
                   <xsd:maxInclusive value="255"></xsd:maxInclusive>
                </xsd:restriction>
             </xsd:simpleType>
          </xsd:attribute>
            <xsd:attribute name="green" use="required">
             <xsd:simpleType>
                <xsd:restriction base="xsd:int">
                   <xsd:minInclusive value="0"></xsd:minInclusive>
                   <xsd:maxInclusive value="255"></xsd:maxInclusive>
                </xsd:restriction>
             </xsd:simpleType>
          </xsd:attribute>
            <xsd:attribute name="red" use="required">
             <xsd:simpleType>
                <xsd:restriction base="xsd:int">
                   <xsd:minInclusive value="0"></xsd:minInclusive>
                   <xsd:maxInclusive value="255"></xsd:maxInclusive>
                </xsd:restriction>
             </xsd:simpleType>
          </xsd:attribute>
        </xsd:complexType>
    </xsd:element>
    
    <xsd:element name="Position" type="xsd:string"></xsd:element>

    <xsd:element name="PlotModelElement">
       <xsd:complexType>
          <xsd:sequence>
             <xsd:element ref="Position" maxOccurs="1" minOccurs="0"></xsd:element>
             <xsd:element ref="Color" maxOccurs="1" minOccurs="0"></xsd:element>
          </xsd:sequence>
          <xsd:attribute name="paramName" type="xsd:string"></xsd:attribute>
          <xsd:attribute name="textSize" type="xsd:string"></xsd:attribute>
          <xsd:attribute name="textFont" type="xsd:string"></xsd:attribute>
          <xsd:attribute name="textStyle" type="xsd:string"></xsd:attribute>
          <xsd:attribute name="symbolSize" type="xsd:int"></xsd:attribute>
       </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== Unidata/awips2-ncep/viz/gov.noaa.nws.ncep.viz.localization/localization/ncep/PlotModels/airep/standard.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<plotModel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="plotModel.xsd"
        plugin="airep" name="standard"       
        svgTemplate="standardPlotModelTemplate.svg">
		
		<!--  This was created from nmap full_standard plot model for ACFT
		 but some params have been commented out since  all the parameters
		 have not been implemented yet for airep 
		 
		  -->
<!--        <PlotModelElement symbolSize="1" textStyle="Bold" 
textFont="Courier" textSize="14" paramName="TMPC">
            <Position>UL</Position>
            <Color red="255" green="0" blue="0"/>
        </PlotModelElement> -->
        <!-- 
        <PlotModelElement symbolSize="1" textStyle="Bold" 
textFont="Courier" textSize="14" paramName="BRBK">
            <Position>MC</Position>
            <Color red="0" green="255" blue="255"/>
        </PlotModelElement>
         -->                
        <PlotModelElement symbolSize="1" textStyle="Bold" 
textFont="Courier" textSize="14" paramName="TPOI">
            <Position>UC</Position>
            <Color red="255" green="255" blue="0"/>
        </PlotModelElement>  
        
        <PlotModelElement symbolSize="1" textStyle="Bold" 
textFont="Courier" textSize="14" paramName="ICSY">
            <Position>UR</Position>
            <Color red="255" green="0" blue="255"/>
        </PlotModelElement>  
        <PlotModelElement symbolSize="1" textStyle="Bold" 
textFont="Courier" textSize="14" paramName="STID">
            <Position>MC</Position>
            <Color red="205" green="133" blue="0"/>
        </PlotModelElement>
        <PlotModelElement symbolSize="1" textStyle="Bold" 
textFont="Courier" textSize="14" paramName="FELV">
            <Position>LC</Position>
            <Color red="0" green="255" blue="0"/>
        </PlotModelElement>
        <PlotModelElement symbolSize="1" textStyle="Bold" 
textFont="Courier" textSize="14" paramName="TBSY">
            <Position>UL</Position>
            <Color red="0" green="178" blue="238"/>
        </PlotModelElement>   
        <!-- <PlotModelElement symbolSize="1" textStyle="Bold" 
textFont="Courier" textSize="14" paramName="CLC1">
            <Position>TC</Position>
            <Color red="0" green="178" blue="238"/>
        </PlotModelElement>     -->  
</plotModel>
